spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concert_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379

cloudinary:
  cloud-name: cgt7r3ab
  api-key: 466694252493158
  api-secret: ${CLOUDINARY_API_SECRET}